INSERT INTO Currency (id, iso_code, country_name) VALUES (1, 'AED', 'United Arab Emirates');
INSERT INTO Currency (id, iso_code, country_name) VALUES (2, 'AUD', 'Australia');
INSERT INTO Currency (id, iso_code, country_name) VALUES (3, 'BGN', 'Bulgaria');
INSERT INTO Currency (id, iso_code, country_name) VALUES (4, 'CAD', 'Canada');
INSERT INTO Currency (id, iso_code, country_name) VALUES (5, 'CHF', 'Switzerland');
INSERT INTO Currency (id, iso_code, country_name) VALUES (6, 'CNH', 'China (Hong Kong)');
INSERT INTO Currency (id, iso_code, country_name) VALUES (7, 'CZK', 'Czech Republic');
INSERT INTO Currency (id, iso_code, country_name) VALUES (8, 'DKK', 'Denmark');
INSERT INTO Currency (id, iso_code, country_name) VALUES (9, 'EUR', 'Euro Area');
INSERT INTO Currency (id, iso_code, country_name) VALUES (10, 'GBP', 'United Kingdom');
INSERT INTO Currency (id, iso_code, country_name) VALUES (11, 'HKD', 'Hong Kong');
INSERT INTO Currency (id, iso_code, country_name) VALUES (12, 'HRK', 'Croatia');
INSERT INTO Currency (id, iso_code, country_name) VALUES (13, 'HUF', 'Hungary');
INSERT INTO Currency (id, iso_code, country_name) VALUES (14, 'ILS', 'Israel');
INSERT INTO Currency (id, iso_code, country_name) VALUES (15, 'JPY', 'Japan');
INSERT INTO Currency (id, iso_code, country_name) VALUES (16, 'MXN', 'Mexico');
INSERT INTO Currency (id, iso_code, country_name) VALUES (17, 'NOK', 'Norway');
INSERT INTO Currency (id, iso_code, country_name) VALUES (18, 'NZD', 'New Zealand');
INSERT INTO Currency (id, iso_code, country_name) VALUES (19, 'PLN', 'Poland');
INSERT INTO Currency (id, iso_code, country_name) VALUES (20, 'RON', 'Romania');
INSERT INTO Currency (id, iso_code, country_name) VALUES (21, 'RUB', 'Russia');
INSERT INTO Currency (id, iso_code, country_name) VALUES (22, 'RSD', 'Serbia');
INSERT INTO Currency (id, iso_code, country_name) VALUES (23, 'SAR', 'Saudi Arabia');
INSERT INTO Currency (id, iso_code, country_name) VALUES (24, 'SEK', 'Sweden');
INSERT INTO Currency (id, iso_code, country_name) VALUES (25, 'SGD', 'Singapore');
INSERT INTO Currency (id, iso_code, country_name) VALUES (26, 'THB', 'Thailand');
INSERT INTO Currency (id, iso_code, country_name) VALUES (27, 'TRY', 'Turkey');
INSERT INTO Currency (id, iso_code, country_name) VALUES (28, 'USD', 'United States');
INSERT INTO Currency (id, iso_code, country_name) VALUES (29, 'ZAR', 'South Africa');

-- Today
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (1, 1, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (2, 2, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (3, 3, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (4, 4, curdate(), '15:30:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (5, 5, curdate(), '10:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (6, 6, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (7, 7, curdate(), '11:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (8, 8, curdate(), '15:30:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (9, 9, curdate(), '16:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (10,10, curdate(), '15:30:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (11,11, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (12,12, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (13,13, curdate(), '11:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (14,14, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (15,15, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (16,16, curdate(), '11:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (17,17, curdate(), '15:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (18,18, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (19,19, curdate(), '10:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (20,20, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (21,21, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (22,22, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (23,23, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (24,24, curdate(), '15:30:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (25,25, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (26,26, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (27,27, curdate(), null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (28,28, curdate(), '16:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (29,29, curdate(), null, true, false);

-- Tomorrow
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (30,1, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (31,2, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (32,3, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (33,4, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (34,5, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (35,6, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (36,7, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (37,8, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (38,9, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (39,10, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (40,11, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (41,12, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (42,13, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (43,14, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (44,15, curdate() + INTERVAL '1' DAY, '15:30:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (45,16, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (46,17, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (47,18, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (48,19, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (49,20, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (50,21, curdate() + INTERVAL '1' DAY, '13:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (51,22, curdate() + INTERVAL '1' DAY, null, true, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (52,23, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (53,24, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (54,25, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (55,26, curdate() + INTERVAL '1' DAY, '09:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (56,27, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (57,28, curdate() + INTERVAL '1' DAY, null, false, true);
INSERT INTO Cut_Off_Time (id, currency_id, cut_off_date, cut_off_time, never_possible, always_possible) VALUES (58,29, curdate() + INTERVAL '1' DAY, '14:00:00', false, false);